<a href="https://colab.research.google.com/github/NirobDas29/learning/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating numpy array


In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
#2d and 3rd numpy
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#dtype
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [8]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
#np.ones and np.zeros
np.ones((3,4))
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#np.random
np.random.random((3,4))

array([[0.39547035, 0.98288642, 0.56958723, 0.47570654],
       [0.25466807, 0.72120996, 0.37739926, 0.72298776],
       [0.43709918, 0.88802455, 0.05312668, 0.16706445]])

In [17]:
#np.linspace
np.linspace(-10,10,10,dtype=int) #-10 to 10 and 10 numbers total

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [15]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
#ndim
a3.ndim   #find dimension

3

In [25]:
#shape  items in every dimension

print(a3.shape)
a3


(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
#size how many numbers in an array
a3.size

8

In [29]:
#itemsize gives memory size like 8 byte 16 bytes
a3.itemsize

8

changing datatypes


In [33]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [35]:
#scalar operation
#arithmetic
a2*2 #works +,-,/......


array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [36]:
#relational
a2>5 #==,=,,=,=>....


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
#vector operations
#arithmetic
a4 = np.arange(1,13).reshape(3,4)
a2 + a4

array([[ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.],
       [17., 19., 21., 23.]])

In [44]:
#min/max/sum/prod
np.max(a2) #like that all of this

np.float64(11.0)

In [48]:
#if it need to ervery row
#0 means column and 1 means row
np.max(a2,axis=1)

array([ 3.,  7., 11.])

In [50]:
#mean/median/std/var
np.mean(a2,axis=1)
np.median(a2,axis=1)


array([1.5, 5.5, 9.5])

In [61]:
#dot product
import numpy as np
a2= np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [62]:
#lon and exponents
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [64]:
##round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[86., 48., 83.],
       [51., 59., 87.]])

In [66]:

a1=np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [67]:
#indexing and slicing
 #as like python

np.int64(9)

In [69]:
#np,nditer -> it makes everything 1D
for i in np.nditer(a4):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [72]:
#transpose
np.transpose(a2)
#same
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
#ravel
#makes any dimention array to 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)


In [78]:
#virtical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
#horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [81]:
#split and stacking different way for working
#horizontal split
np.hsplit(a4,2)
#vertical split
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]